version: '3'
services:
  mongo:
    image: mongo
    networks:
      - movie-network
  web-film:
    build: .
    ports:
      - 80:3000
    networks:
      - movie-network
    environment:
      - MONGO_HOST=mongo
networks:
  movie-network:
    driver: bridge
