version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./media:/usr/share/nginx/html/media

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./media:/app/media
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
